'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const assert = require('node:assert/strict');
const workspace = path.resolve(__dirname, '../../..');
const builder = fs.readFileSync(path.join(workspace, 'KimchilyUnityRuntime/Assets/Editor/WebRuntimeBuilder.cs'), 'utf8');
const block = builder.slice(builder.indexOf('// Import real TypeScript'), builder.indexOf('AssetDatabase.ImportAsset(ScriptPath'));
const literals = block.split('\n').map(line => line.trim()).filter(line => /^"/.test(line));
const source = literals.map(line => JSON.parse(line.replace(/\s*\+\s*$/, '').replace(/\);$/, ''))).join('');
assert.match(source, /export default class WebDemo/);
const project = path.join(__dirname, 'artifacts', 'DemoCompilerCheck');
fs.mkdirSync(path.join(project, 'Assets'), { recursive: true });
fs.writeFileSync(path.join(project, 'Assets/WebDemo.ts'), source);
const output = path.join(project, 'Library/KimchilyTypeScript/compiled.json');
const compiler = path.join(workspace, 'KimchilySDK/Packages/com.kimchily.typescript/Tools~/Compiler/compile.cjs');
const run = spawnSync(process.execPath, [compiler, '--project-root', project, '--entry', 'Assets/WebDemo.ts', '--output', output], { encoding: 'utf8' });
assert.equal(run.status, 0, run.stderr || run.stdout);
const result = JSON.parse(fs.readFileSync(output, 'utf8'));
assert.equal(result.compiledSuccessfully, true, JSON.stringify(result.diagnostics));
assert.equal(result.className, 'WebDemo');
assert.ok(result.modules[0].source.includes('class WebDemo'));
assert.ok(result.modules[0].source.includes('new Map'));
assert.ok(result.modules[0].source.includes('*Ready'));
console.log('WEB_DEMO_TYPESCRIPT_COMPILE_PASS', result.compilerVersion, result.modules.length, 'module');
