<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.25.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServerCore\ServerCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Server\Packet\Protocol.cs" Link="Packet\Protocol.cs" />
  </ItemGroup>

</Project>
