<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Kimchily.Server.Core/Kimchily.Server.Core.csproj" />
    <ProjectReference Include="../../src/Kimchily.Server.Host/Kimchily.Server.Host.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
