// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpaChRQTEFZRVJfQ0hBTVBJT05fVFlQ",
            "RRIUChBQTEFZRVJfVFlQRV9OT05FEAASFQoRUExBWUVSX1RZUEVfQU5OSUUQ",
            "ARIVChFQTEFZRVJfVFlQRV9HQVJFThACKl4KC09CSkVDVF9UWVBFEgsKB1VO",
            "S05PV04QABIKCgZQTEFZRVIQARIOCgpBTExZUExBWUVSEAISDwoLRU5FTVlQ",
            "TEFZRVIQAxIKCgZNSU5JT04QBBIJCgVUT1dFUhAFKmgKEU9CSkVDVF9TVEFU",
            "RV9UWVBFEhoKFk9CSkVDVF9TVEFURV9UWVBFX0lETEUQABIaChZPQkpFQ1Rf",
            "U1RBVEVfVFlQRV9NT1ZFEAESGwoXT0JKRUNUX1NUQVRFX1RZUEVfU0tJTEwQ",
            "AiqqBgoSTU9WRV9SRUpFQ1RfUkVBU09OEhsKF01PVkVfUkVKRUNUX1JFQVNP",
            "Tl9OT05FEAASIAocTU9WRV9SRUpFQ1RfUkVBU09OX05PX1BMQVlFUhABEh4K",
            "Gk1PVkVfUkVKRUNUX1JFQVNPTl9OT19ST09NEAISJAogTU9WRV9SRUpFQ1Rf",
            "UkVBU09OX1JPT01fTUlTTUFUQ0gQAxIrCidNT1ZFX1JFSkVDVF9SRUFTT05f",
            "SU5WQUxJRF9QTEFZRVJfU1RBVEUQBBInCiNNT1ZFX1JFSkVDVF9SRUFTT05f",
            "SU5WQUxJRF9TRVFVRU5DRRAFEikKJU1PVkVfUkVKRUNUX1JFQVNPTl9JTlZB",
            "TElEX0NPT1JESU5BVEUQBhIuCipNT1ZFX1JFSkVDVF9SRUFTT05fTkFWSUdB",
            "VElPTl9NQVBfTUlTTUFUQ0gQBxIvCitNT1ZFX1JFSkVDVF9SRUFTT05fTkFW",
            "SUdBVElPTl9IQVNIX01JU01BVENIEAgSMAosTU9WRV9SRUpFQ1RfUkVBU09O",
            "X09VVFNJREVfTkFWSUdBVElPTl9CT1VORFMQCRIqCiZNT1ZFX1JFSkVDVF9S",
            "RUFTT05fREVTVElOQVRJT05fQkxPQ0tFRBAKEi4KKk1PVkVfUkVKRUNUX1JF",
            "QVNPTl9OT19ORUFSQllfV0FMS0FCTEVfQ0VMTBALEisKJ01PVkVfUkVKRUNU",
            "X1JFQVNPTl9NT1ZFTUVOVF9OT1RfQUxMT1dFRBAMEiMKH01PVkVfUkVKRUNU",
            "X1JFQVNPTl9TRVJWRVJfRVJST1IQDRIeChpNT1ZFX1JFSkVDVF9SRUFTT05f",
            "Tk9fUEFUSBAOEjEKLU1PVkVfUkVKRUNUX1JFQVNPTl9QQVRIX1NFQVJDSF9M",
            "SU1JVF9FWENFRURFRBAPEiQKIE1PVkVfUkVKRUNUX1JFQVNPTl9QQVRIX1RP",
            "T19MT05HEBASLworTU9WRV9SRUpFQ1RfUkVBU09OX0lOVkFMSURfTkFWSUdB",
            "VElPTl9TVEFSVBAREiMKH01PVkVfUkVKRUNUX1JFQVNPTl9SQVRFX0xJTUlU",
            "RUQQEiquAQoXTU9WRU1FTlRfU05BUFNIT1RfU1RBVEUSIwofTU9WRU1FTlRf",
            "U05BUFNIT1RfU1RBVEVfVU5LTk9XThAAEiIKHk1PVkVNRU5UX1NOQVBTSE9U",
            "X1NUQVRFX01PVklORxABEiMKH01PVkVNRU5UX1NOQVBTSE9UX1NUQVRFX0FS",
            "UklWRUQQAhIlCiFNT1ZFTUVOVF9TTkFQU0hPVF9TVEFURV9DQU5DRUxMRUQQ",
            "A0IbqgIYR29vZ2xlLlByb3RvYnVmLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.PLAYER_CHAMPION_TYPE), typeof(global::Google.Protobuf.Protocol.OBJECT_TYPE), typeof(global::Google.Protobuf.Protocol.OBJECT_STATE_TYPE), typeof(global::Google.Protobuf.Protocol.MOVE_REJECT_REASON), typeof(global::Google.Protobuf.Protocol.MOVEMENT_SNAPSHOT_STATE), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PLAYER_CHAMPION_TYPE {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] PlayerTypeNone = 0,
    [pbr::OriginalName("PLAYER_TYPE_ANNIE")] PlayerTypeAnnie = 1,
    [pbr::OriginalName("PLAYER_TYPE_GAREN")] PlayerTypeGaren = 2,
  }

  public enum OBJECT_TYPE {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 본인 캐릭터
    /// </summary>
    [pbr::OriginalName("PLAYER")] Player = 1,
    /// <summary>
    /// 아군 플레이어
    /// </summary>
    [pbr::OriginalName("ALLYPLAYER")] Allyplayer = 2,
    /// <summary>
    /// 적군 플레이어
    /// </summary>
    [pbr::OriginalName("ENEMYPLAYER")] Enemyplayer = 3,
    /// <summary>
    /// 미니언 (추후 확장 가능)
    /// </summary>
    [pbr::OriginalName("MINION")] Minion = 4,
    /// <summary>
    /// 타워 (추후 확장 가능)
    /// </summary>
    [pbr::OriginalName("TOWER")] Tower = 5,
  }

  public enum OBJECT_STATE_TYPE {
    [pbr::OriginalName("OBJECT_STATE_TYPE_IDLE")] Idle = 0,
    [pbr::OriginalName("OBJECT_STATE_TYPE_MOVE")] Move = 1,
    [pbr::OriginalName("OBJECT_STATE_TYPE_SKILL")] Skill = 2,
  }

  public enum MOVE_REJECT_REASON {
    [pbr::OriginalName("MOVE_REJECT_REASON_NONE")] None = 0,
    [pbr::OriginalName("MOVE_REJECT_REASON_NO_PLAYER")] NoPlayer = 1,
    [pbr::OriginalName("MOVE_REJECT_REASON_NO_ROOM")] NoRoom = 2,
    [pbr::OriginalName("MOVE_REJECT_REASON_ROOM_MISMATCH")] RoomMismatch = 3,
    [pbr::OriginalName("MOVE_REJECT_REASON_INVALID_PLAYER_STATE")] InvalidPlayerState = 4,
    [pbr::OriginalName("MOVE_REJECT_REASON_INVALID_SEQUENCE")] InvalidSequence = 5,
    [pbr::OriginalName("MOVE_REJECT_REASON_INVALID_COORDINATE")] InvalidCoordinate = 6,
    [pbr::OriginalName("MOVE_REJECT_REASON_NAVIGATION_MAP_MISMATCH")] NavigationMapMismatch = 7,
    [pbr::OriginalName("MOVE_REJECT_REASON_NAVIGATION_HASH_MISMATCH")] NavigationHashMismatch = 8,
    [pbr::OriginalName("MOVE_REJECT_REASON_OUTSIDE_NAVIGATION_BOUNDS")] OutsideNavigationBounds = 9,
    [pbr::OriginalName("MOVE_REJECT_REASON_DESTINATION_BLOCKED")] DestinationBlocked = 10,
    [pbr::OriginalName("MOVE_REJECT_REASON_NO_NEARBY_WALKABLE_CELL")] NoNearbyWalkableCell = 11,
    [pbr::OriginalName("MOVE_REJECT_REASON_MOVEMENT_NOT_ALLOWED")] MovementNotAllowed = 12,
    [pbr::OriginalName("MOVE_REJECT_REASON_SERVER_ERROR")] ServerError = 13,
    [pbr::OriginalName("MOVE_REJECT_REASON_NO_PATH")] NoPath = 14,
    [pbr::OriginalName("MOVE_REJECT_REASON_PATH_SEARCH_LIMIT_EXCEEDED")] PathSearchLimitExceeded = 15,
    [pbr::OriginalName("MOVE_REJECT_REASON_PATH_TOO_LONG")] PathTooLong = 16,
    [pbr::OriginalName("MOVE_REJECT_REASON_INVALID_NAVIGATION_START")] InvalidNavigationStart = 17,
    [pbr::OriginalName("MOVE_REJECT_REASON_RATE_LIMITED")] RateLimited = 18,
  }

  public enum MOVEMENT_SNAPSHOT_STATE {
    [pbr::OriginalName("MOVEMENT_SNAPSHOT_STATE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("MOVEMENT_SNAPSHOT_STATE_MOVING")] Moving = 1,
    [pbr::OriginalName("MOVEMENT_SNAPSHOT_STATE_ARRIVED")] Arrived = 2,
    [pbr::OriginalName("MOVEMENT_SNAPSHOT_STATE_CANCELLED")] Cancelled = 3,
  }

  #endregion

}

#endregion Designer generated code
