// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpaChRQTEFZRVJfQ0hBTVBJT05fVFlQ",
            "RRIUChBQTEFZRVJfVFlQRV9OT05FEAASFQoRUExBWUVSX1RZUEVfQU5OSUUQ",
            "ARIVChFQTEFZRVJfVFlQRV9HQVJFThACKl4KC09CSkVDVF9UWVBFEgsKB1VO",
            "S05PV04QABIKCgZQTEFZRVIQARIOCgpBTExZUExBWUVSEAISDwoLRU5FTVlQ",
            "TEFZRVIQAxIKCgZNSU5JT04QBBIJCgVUT1dFUhAFKmgKEU9CSkVDVF9TVEFU",
            "RV9UWVBFEhoKFk9CSkVDVF9TVEFURV9UWVBFX0lETEUQABIaChZPQkpFQ1Rf",
            "U1RBVEVfVFlQRV9NT1ZFEAESGwoXT0JKRUNUX1NUQVRFX1RZUEVfU0tJTEwQ",
            "AkIbqgIYR29vZ2xlLlByb3RvYnVmLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.PLAYER_CHAMPION_TYPE), typeof(global::Google.Protobuf.Protocol.OBJECT_TYPE), typeof(global::Google.Protobuf.Protocol.OBJECT_STATE_TYPE), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PLAYER_CHAMPION_TYPE {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] PlayerTypeNone = 0,
    [pbr::OriginalName("PLAYER_TYPE_ANNIE")] PlayerTypeAnnie = 1,
    [pbr::OriginalName("PLAYER_TYPE_GAREN")] PlayerTypeGaren = 2,
  }

  public enum OBJECT_TYPE {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 본인 캐릭터
    /// </summary>
    [pbr::OriginalName("PLAYER")] Player = 1,
    /// <summary>
    /// 아군 플레이어
    /// </summary>
    [pbr::OriginalName("ALLYPLAYER")] Allyplayer = 2,
    /// <summary>
    /// 적군 플레이어
    /// </summary>
    [pbr::OriginalName("ENEMYPLAYER")] Enemyplayer = 3,
    /// <summary>
    /// 미니언 (추후 확장 가능)
    /// </summary>
    [pbr::OriginalName("MINION")] Minion = 4,
    /// <summary>
    /// 타워 (추후 확장 가능)
    /// </summary>
    [pbr::OriginalName("TOWER")] Tower = 5,
  }

  public enum OBJECT_STATE_TYPE {
    [pbr::OriginalName("OBJECT_STATE_TYPE_IDLE")] Idle = 0,
    [pbr::OriginalName("OBJECT_STATE_TYPE_MOVE")] Move = 1,
    [pbr::OriginalName("OBJECT_STATE_TYPE_SKILL")] Skill = 2,
  }

  #endregion

}

#endregion Designer generated code
